In [10]:
library("proxy")
library("dtw")
library("rucrdtw")

# Test of fastDTW

Our main function here is similarity_TS. 
* Input:
    * Data Matrix of size $(\sum_{i}^{n}T_{i}) \times p$
    * One of the following
        * len_time: A sequence of $T_{i}$, i=1,2...n; $T_{i}$ are integers here.
        * time_cut : The first time of each unit $(1,T_{1}+1,T_{1}+T_{2}+1,...)$ (not implemented yet)
    * type: The method used when computing distance. This includes "L2" and so on (others not implemented)
        
* Method:
    * Z score normalize each time series, say time 1 to $T_{1}$ for feature 1.
    * Calculate the distance measure according to type with each of n time series, denoted by $d_{i}$
    * Calculate the average estimate of distance of time series as 
    $$d = \frac{\sum_{i=1}^{n}d_{i}T_{i}}{\sum_{i=1}^{n}T_{i}}$$
    * The similarity between the two time series is given by $$\frac{1}{1+d}$$
    
* Output: The $\textbf{similarity}$ (inverse relationship with distance) matrix between features (time series generator) with entries in $[0,1]$. The reason for making it smaller than 1 is that we will raise it to the power $\beta$ later.
* Remark: 
    * (Important!) If the original data has certain time series with the same values, normalized_X will have NA values because in the Z score normalization, $\sigma = 0$. This case should be solved in the data processing step.
    * Maybe later we need the exact time (instead of the index of a certain time in one time series) since some measure requires exact time.
    * After this step, the similarity is raised to the power $\beta$ and then used for calculate TOM

# Functions

In [33]:
# Normalize each time series (not a column)
normalize_TS = function(X,len_time){
    normalized_X = matrix(0,dim(X)[1],dim(X)[2])
    flag = 1 # record the first index of the current time series
    for (t in len_time){
        normalized_X[flag:(flag+t-1),] = scale(X[flag:(flag+t-1),])
        flag = flag + t
    }
    return (normalized_X)
}

# The main function                                                 
# compute similarity using different measure
similarity_TS = function(X,len_time,type){
    p = dim(X)[2] # num of features
    n = length(len_time) # number of samples
    
    ## type = cor, no need to normalize ##
    if (type == "cor"){
        # first compute distance matrix
        if (n==1){
            cor_mat = cor(X)
        }else{
            # cor_mat can be computed like a vector! but I have to create it
            cor_mat = cor(X[1:len_time[1],])*len_time[1]
            flag = 1+len_time[1] # the first time index of the current sample
            for (sample in 2:n){
                cor_mat = (cor_mat + 
            cor(X[flag:(flag+len_time[sample]-1),])*len_time[sample])
                
                flag = flag+len_time[sample]
            }
            cor_mat = cor_mat/(sum(len_time))
        }     
           
        return (cor_mat)
        } # end "cor"
    
     ## type = fastDTW, no need to normalize ##
    if (type == "fastDTW"){
        # pre-allocate memory
        dist_mat = matrix(0,p,p)
        if (n==1){
            for (i in 1:(p-1)){
                for (j in (i+1):p){
                    dist_mat[i,j] = ucrdtw_vv(X[,i], X[,j], 0.05)$distance
                }
            }
        }else{
            flag = 1 # the first time index of the current sample
            for (sample in 1:n){
                for (i in 1:(p-1)){
                    for (j in (i+1):p){
                        dist_mat[i,j] = (dist_mat[i,j]
                        +(ucrdtw_vv(X[flag:(flag+len_time[sample]-1),i], 
                                                  X[flag:(flag+len_time[sample]-1),j],
                                                  0.05)$distance)*len_time[sample])
                    }
                }                
                flag = flag+len_time[sample]
            }
            dist_mat = dist_mat/(sum(len_time))
        }
        # complete the matrix (diag=0 automatically)
        dist_mat[lower.tri(dist_mat)] = t(dist_mat)[lower.tri(dist_mat)]
        
        # transform dist to similarity
        sim_matrix = 1/(1+dist_mat)
        
        return (sim_matrix)
        } # end "fastDTW"
    
    #### data Z score normaliztion #####
    X = normalize_TS(X,len_time) # normalize time series
    #check for missing value (may due to sigma=0)
    tmp = sum(is.na(X))
    if(tmp>0){
        stop(sprintf("There are %d missing values in normalized X",tmp))
    }
    ### end normalization ###
    
    
    # "L2" using dist(M) which computes dist between rows of M
    if (type == "L2"|type == "Euclidean"){
        # first compute distance matrix
        if (n==1){
            dist_obj = dist(t(X),method = "euclidean")
        }else{
            # dist_obj can be computed like a vector! but I have to create it
            dist_obj = dist(t(X[1:len_time[1],]))*len_time[1]
            flag = 1+len_time[1] # the first time index of the current sample
            for (sample in 2:n){
                dist_obj = (dist_obj + 
            dist(t(X[flag:(flag+len_time[sample]-1),]))*len_time[sample])
                
                flag = flag+len_time[sample]
            }
            dist_obj = dist_obj/(sum(len_time))
        }     
    
        # transform dist to similarity
        sim_obj = 1/(1+dist_obj)
        # similarity matrix
        sim_matrix = as.matrix(sim_obj)
        diag(sim_matrix) = 1
        
        return (sim_matrix)
        } # end "L2"
    
    # "dtw" using dtwDist(M) which computes dist between rows of M
    if (type == "dtw" | type == "DTW"){
        # first compute distance matrix
        if (n==1){
            dist_obj = dtwDist(t(X))
        }else{
            # dist_obj can be computed like a vector! but I have to create it
            dist_obj = dtwDist(t(X[1:len_time[1],]))*len_time[1]
            flag = 1+len_time[1] # the first time index of the current sample
            for (sample in 2:n){
                dist_obj = (dist_obj + 
            dtwDist(t(X[flag:(flag+len_time[sample]-1),]))*len_time[sample])
                
                flag = flag+len_time[sample]
            }
            dist_obj = dist_obj/(sum(len_time))
        }     
    
        # transform dist to similarity
        sim_obj = 1/(1+dist_obj)
        # similarity matrix
        sim_matrix = as.matrix(sim_obj)
        diag(sim_matrix) = 1
        
        return (sim_matrix)
        } # end "dtw"
    
    
    stop("The type is not availble")
    
    }

# For Testing

In [34]:
# For test1 (small)
# data matrix n=2 p=3
X = matrix(0,5,3)
len_time = c(3,2) # T1=3, T2=2
X[1:3,1] = c(1,1,1.1)
X[1:3,2] = c(2,2,2.2)
X[1:3,3] = c(1,0.5,1.5)
X[4:5,1] = c(1.2,1.3)
X[4:5,2] = c(2,2.2)
X[4:5,3] = c(5,15)
X

[,1] [,2] [,3]
[1,] 1.0  2.0   1.0
[2,] 1.0  2.0   0.5
[3,] 1.1  2.2   1.5
[4,] 1.2  2.0   5.0
[5,] 1.3  2.2  15.0

In [25]:
X = matrix(runif(15),5,3)

In [35]:
similarity_TS(X,len_time,"DTW")

[,1]      [,2]      [,3]     
[1,] 1.0000000 1.0000000 0.4903811
[2,] 1.0000000 1.0000000 0.4903811
[3,] 0.4903811 0.4903811 1.0000000

In [38]:
# For test3 (bigger)
n = 100 # samples
T = 5 # time each samples
p = 100 # features
len_time = rep(T,n)
X = matrix(rnorm(n*T*p),n*T,p) # (n*T)*p

In [39]:
start_time <- Sys.time()
sim_mat = similarity_TS(X,len_time,"fastDTW")
sim_mat
end_time <- Sys.time()

end_time - start_time

[,1]      [,2]      [,3]      [,4]      [,5]      [,6]      [,7]     
 [1,] 1.0000000 0.2527188 0.2513648 0.2499762 0.2437693 0.2514962 0.2541645
 [2,] 0.2527188 1.0000000 0.2478862 0.2379116 0.2530776 0.2415487 0.2411045
 [3,] 0.2513648 0.2478862 1.0000000 0.2496661 0.2528613 0.2484438 0.2537876
 [4,] 0.2499762 0.2379116 0.2496661 1.0000000 0.2482838 0.2497044 0.2576820
 [5,] 0.2437693 0.2530776 0.2528613 0.2482838 1.0000000 0.2532800 0.2472725
 [6,] 0.2514962 0.2415487 0.2484438 0.2497044 0.2532800 1.0000000 0.2489663
 [7,] 0.2541645 0.2411045 0.2537876 0.2576820 0.2472725 0.2489663 1.0000000
 [8,] 0.2470415 0.2486544 0.2438618 0.2489941 0.2508542 0.2543534 0.2599371
 [9,] 0.2426133 0.2433319 0.2435716 0.2491325 0.2503526 0.2542351 0.2508128
[10,] 0.2438680 0.2498186 0.2549035 0.2484126 0.2394097 0.2461543 0.2573523
[11,] 0.2460570 0.2458525 0.2514143 0.2437311 0.2415306 0.2451330 0.2520274
[12,] 0.2366010 0.2552063 0.2416833 0.2488447 0.2473892 0.2452844 0.2468154
[13,] 0.2435363 0.2549254 0.2453968 0.2551233 0.2583118 0.2543159 0.2422284
[14,] 0.2426057 0.2501910 0.2448527 0.2402698 0.2457553 0.2397848 0.2567778
[15,] 0.2453036 0.2521945 0.2396109 0.2412813 0.2603639 0.2444920 0.2512977
[16,] 0.2487272 0.2472151 0.2475879 0.2484971 0.2496785 0.2479918 0.2433502
[17,] 0.2606276 0.2484296 0.2433118 0.2415485 0.2486208 0.2504547 0.2473166
[18,] 0.2456038 0.2489952 0.2534120 0.2419681 0.2550318 0.2668675 0.2510844
[19,] 0.2531687 0.2519285 0.2504691 0.2442426 0.2455307 0.2516545 0.2529039
[20,] 0.2407759 0.2393804 0.2461192 0.2504216 0.2453107 0.2438265 0.2530777
[21,] 0.2409697 0.2582741 0.2473699 0.2517464 0.2472228 0.2441723 0.2519644
[22,] 0.2484339 0.2610069 0.2478876 0.2492998 0.2565514 0.2434364 0.2461917
[23,] 0.2509623 0.2394139 0.2415282 0.2465940 0.2439418 0.2493834 0.2537749
[24,] 0.2435184 0.2473202 0.2498878 0.2533710 0.2440634 0.2393473 0.2546435
[25,] 0.2449908 0.2384911 0.2499998 0.2526232 0.2418979 0.2426182 0.2382144
[26,] 0.2458259 0.2467624 0.2499980 0.2543406 0.2551332 0.2468157 0.2533446
[27,] 0.2545481 0.2447490 0.2449147 0.2516272 0.2525177 0.2488890 0.2540565
[28,] 0.2538026 0.2513820 0.2405637 0.2479113 0.2445055 0.2394023 0.2514221
[29,] 0.2491857 0.2438114 0.2488733 0.2548103 0.2494843 0.2506660 0.2533535
[30,] 0.2436149 0.2397369 0.2493347 0.2434126 0.2363369 0.2423679 0.2594684
[31,] ...       ...       ...       ...       ...       ...       ...      
[32,] 0.2558803 0.2567751 0.2393140 0.2572420 0.2341442 0.2457537 0.2483025
[33,] 0.2454210 0.2438384 0.2417651 0.2456724 0.2483609 0.2539010 0.2452433
[34,] 0.2451158 0.2539830 0.2503111 0.2533364 0.2506432 0.2541220 0.2509225
[35,] 0.2501608 0.2474611 0.2558702 0.2448798 0.2550921 0.2451569 0.2430132
[36,] 0.2533877 0.2512271 0.2434197 0.2384861 0.2384248 0.2527976 0.2469598
[37,] 0.2507431 0.2489195 0.2510293 0.2421879 0.2452115 0.2497010 0.2570347
[38,] 0.2474271 0.2496953 0.2489787 0.2394747 0.2443742 0.2493092 0.2539433
[39,] 0.2418485 0.2437858 0.2434342 0.2600789 0.2504017 0.2472408 0.2429938
[40,] 0.2396809 0.2501215 0.2427687 0.2393293 0.2429502 0.2379882 0.2475636
[41,] 0.2553101 0.2519408 0.2433970 0.2421004 0.2535668 0.2417615 0.2491906
[42,] 0.2514214 0.2474428 0.2484846 0.2529222 0.2530179 0.2441191 0.2509146
[43,] 0.2505339 0.2492770 0.2437783 0.2473222 0.2502868 0.2431728 0.2532314
[44,] 0.2474042 0.2497642 0.2512295 0.2540327 0.2446191 0.2451079 0.2505693
[45,] 0.2481151 0.2420355 0.2487216 0.2408537 0.2470856 0.2350964 0.2405727
[46,] 0.2470415 0.2462653 0.2423131 0.2411374 0.2449621 0.2427053 0.2407712
[47,] 0.2472147 0.2480376 0.2527781 0.2396784 0.2428271 0.2525388 0.2500707
[48,] 0.2501318 0.2450215 0.2581832 0.2441062 0.2587136 0.2438010 0.2569017
[49,] 0.2442668 0.2461395 0.2455827 0.2499571 0.2469627 0.2594497 0.2429964
[50,] 0.2371498 0.2453604 0.2483306 0.2539756 0.2476896 0.2357540 0.2440048
[51,] 0.2520178 0.2413433 0.2557290 0.2460965 0.2481594 0.2447906 0.2479331
[52,] 0.2494234 0.2401578 0.2458890 0.2428195 0.249848

Time difference of 56.95113 secs

In [54]:
similarity_TS(X,len_time,"L2")

1         2         3        
1 1.0000000 1.0000000 0.6948157
2 1.0000000 1.0000000 0.6948157
3 0.6948157 0.6948157 1.0000000

# Test of speed

In [48]:
system.time(dist(t(X),method="tsDistances",distance="euclidean"))

ERROR: Error in .get_entry_index(name, stop_if_missing): Entry "tsDistances" not in registry.


Timing stopped at: 0 0 0


In [24]:
system.time(dist(t(X)))

   user  system elapsed 
   0.03    0.00    0.03 

In [23]:
system.time(TSDatabaseDistances(t(X),distance="euclidean"))

   user  system elapsed 
   4.79    0.14    5.89 